In [1]:
import pandas as pd
import numpy as np

In [19]:
#Create an empty series

s= pd.Series()
print(s)
print(type(s))

Series([], dtype: float64)
<class 'pandas.core.series.Series'>


In [3]:
#Create a series from ndarray
data= np.array(['a','b','e','d'])
s= pd.Series(data)
print(data, '\n')
print(s)

['a' 'b' 'e' 'd'] 

0    a
1    b
2    e
3    d
dtype: object


In [21]:
#Create a series from ndarray with index parameter
data=np.array(['a','b','c','d'])
s=pd.Series(data,index=[100, 'a', 102, 'b'])#range(100,104)
print(s)

100    a
a      b
102    c
b      d
dtype: object


In [5]:
#Create from dictionary
data={'a':0,'b':1,'c':2}
s=pd.Series(data,dtype=np.int32)
print(s)
print(s['c'])
#print(a[0])

a    0
b    1
c    2
dtype: int32
2


In [26]:
#create a series from dict
data={'a':0,'b':1,'c':2}
s=pd.Series(data,index=['b','c','d','a']) #NaN means not a number
print(s)
print(s['a'])

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64
0.0


In [7]:
#Create a series from scale

s=pd.Series(4,index=[0,1,2,3])
print(s)

0    4
1    4
2    4
3    4
dtype: int64


-------------------------------------
----------------------------------------
----------------------------------------
Accessing Data From Series with Positions


In [27]:
s= pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [9]:
#retieve a single element
print(s[0])

1


In [10]:
#retieve First 3 elements
print(s[:3])

a    1
b    2
c    3
dtype: int64


In [11]:
#retieve the last three elements
print(s[-3:])

c    3
d    4
e    5
dtype: int64


---------------------------------
------------------------------
Retrieve Data Using Label(Index)

In [12]:
s= pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [13]:
#Retrieve a single element
print(s['a'])

1


In [29]:
#retrieve multiple elements
print(s['a':'c'])

a    1
b    2
c    3
dtype: int64


In [15]:
#Passing non-existig element
print(s['f'])

KeyError: 'f'

# DATA FRAME

In [33]:
data=[1,2,3,4,5]
df= pd.DataFrame(data)
print(df)
print(type(df))

   0
0  1
1  2
2  3
3  4
4  5
<class 'pandas.core.frame.DataFrame'>


'''OPERATIONS:
    Slicing dataFrames.
    Changing Index.
    Joining and merging. 
    Changing Column Headers.
    Data Conversions.

In [36]:
data=[['Andrew',10],['Lisa',13]]
#df= pd.DataFrame(data)
df= pd.DataFrame(data, columns=['Name', 'Age'])
print(df)

     Name  Age
0  Andrew   10
1    Lisa   13


In [38]:
data={'Name':['Phoebe','Ross','Joey','Monica','Rachel'],'Age':[30,17,12,32,31]}
df=pd.DataFrame(data, index= [1,2,3,4,5])#or range(1,6)
print(df)

     Name  Age
1  Phoebe   30
2    Ross   17
3    Joey   12
4  Monica   32
5  Rachel   31


In [39]:
print(df['Name'])

1    Phoebe
2      Ross
3      Joey
4    Monica
5    Rachel
Name: Name, dtype: object


### Create from a list of dict

In [41]:
data=[{'a':10,'b':20},{'a':15,'b':25,'c':35}]
df= pd.DataFrame(data)
print(df)

    a   b     c
0  10  20   NaN
1  15  25  35.0


In [42]:
data=[{'a':10,'b':20},{'a':15,'b':25,'c':35}]
df= pd.DataFrame(data,index=['Primary','Secondary'])
print(df)

            a   b     c
Primary    10  20   NaN
Secondary  15  25  35.0


In [43]:
#with two coulmn indices values same as dictonary keys
df1=pd.DataFrame(data,index=['Primary','Secondary'],columns=['b','a'])
print(df1)

            b   a
Primary    20  10
Secondary  25  15


In [44]:
#with two coulmn indices with one index with other name
df2=pd.DataFrame(data,index=['Primary','Secondary'],columns=['a','b1'])
print(df2)

            a  b1
Primary    10 NaN
Secondary  15 NaN


In [46]:
#create a data frame from a dict of series
d={'one':pd.Series([1,2,3],index=['b', 'c', 'd']),
  'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df=pd.DataFrame(d)
print(df)

   one  two
a  NaN    1
b  1.0    2
c  2.0    3
d  3.0    4


------------#column Selection---------


In [49]:
#----------Column addition--------
#ADDING A NEW COLUMN TO AN EXISTING DATA FRAME OBJECT WITH
#COLUMN LABLED BY PASSING NEW SERIES

print("adding a new column by passing a series")
df['Three']= pd.Series([10,20,30],index=['a','b','e'])
print(df)

adding a new column by passing a series
   one  two  Three  Four
a  NaN    1   10.0   NaN
b  1.0    2   20.0  21.0
c  2.0    3    NaN   NaN
d  3.0    4    NaN   NaN


In [50]:
print("Add new column using existing columns in the data frame")
df['Four']=df['one']+df['Three']
print(df)

Add new column using existing columns in the data frame
   one  two  Three  Four
a  NaN    1   10.0   NaN
b  1.0    2   20.0  21.0
c  2.0    3    NaN   NaN
d  3.0    4    NaN   NaN


------------Column Deletion----------------

In [51]:
#Using del function
del df['one']
print(df)

   two  Three  Four
a    1   10.0   NaN
b    2   20.0  21.0
c    3    NaN   NaN
d    4    NaN   NaN


In [52]:
#using pop function
x=df.pop('two')
print(x)
print(df)


a    1
b    2
c    3
d    4
Name: two, dtype: int64
   Three  Four
a   10.0   NaN
b   20.0  21.0
c    NaN   NaN
d    NaN   NaN


------------------Row Selection , Addition and Deletion--------------

In [53]:
#-----------Selection by label
d= { 'one':pd.Series([1,2,3],index=['a','b','c']),
   'two': pd.Series([1,2,3,4],index=['a','b','c','d'])}

df= pd.DataFrame(d)
print(df)
print('\n')
print(df.loc['b'])

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


one    2.0
two    2.0
Name: b, dtype: float64


In [55]:
#Selection by integer location
d= { 'one':pd.Series([1,2,3],index=['a','b','c']),
   'two': pd.Series([1,2,3,4],index=['a','b','c','d'])}

df= pd.DataFrame(d)
print(df)
print(df.iloc[1])

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4
one    2.0
two    2.0
Name: b, dtype: float64


In [56]:
#Slicing of rows
d= { 'one':pd.Series([1,2,3],index=['a','b','c']),
   'two': pd.Series([1,2,3,4],index=['a','b','c','d'])}

df= pd.DataFrame(d)
print(df[2:4])

   one  two
c  3.0    3
d  NaN    4


In [60]:
#--------------Addition of dfs
df=pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
df2=pd.DataFrame([[5,6],[7,8]],columns=['b','d'])

print(df)

   a  b
0  1  2
1  3  4


In [61]:
print(df2)

   b  d
0  5  6
1  7  8


In [63]:
d3=df.join(df2, lsuffix='1')
print(d3,'\n')


   a  b1  b  d
0  1   2  5  6
1  3   4  7  8 



In [68]:
#--------------Addition of Rows
df=pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
df2=pd.DataFrame([[5,6],[7,8]],columns=['c','d'])

print(df)
print('\n')
print(df2)

   a  b
0  1  2
1  3  4


   c  d
0  5  6
1  7  8


In [69]:
df3=df.append(df2, sort=True)
print(df3)

     a    b    c    d
0  1.0  2.0  NaN  NaN
1  3.0  4.0  NaN  NaN
0  NaN  NaN  5.0  6.0
1  NaN  NaN  7.0  8.0


In [78]:
df4=df.append(df2, sort='False', ignore_index='True')
print(df4)

     a    b    c    d
0  1.0  2.0  NaN  NaN
1  3.0  4.0  NaN  NaN
2  NaN  NaN  5.0  6.0
3  NaN  NaN  7.0  8.0


In [ ]:
#--------------------Deletion of Rows-------------

In [ ]:
print(df,'\n')
print(df2)

In [79]:
df=df.append(df2)
print(df)

     a    b    c    d
0  1.0  2.0  NaN  NaN
1  3.0  4.0  NaN  NaN
0  NaN  NaN  5.0  6.0
1  NaN  NaN  7.0  8.0


C:\Users\satvi\Anaconda3\lib\site-packages\pandas\core\frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


In [80]:
#drop rows with label zero
df= df.drop(0)
print(df)

     a    b    c    d
1  3.0  4.0  NaN  NaN
1  NaN  NaN  7.0  8.0


# Missing Data

In [89]:
df=pd.DataFrame(4,index=['a','c','e','f','h'],columns=['one','two','three'])
print(df, '\n\n')
df=df.reindex(['a','b','c','d','e','f','g','h'])

print(df)

   one  two  three
a    4    4      4
c    4    4      4
e    4    4      4
f    4    4      4
h    4    4      4 


   one  two  three
a  4.0  4.0    4.0
b  NaN  NaN    NaN
c  4.0  4.0    4.0
d  NaN  NaN    NaN
e  4.0  4.0    4.0
f  4.0  4.0    4.0
g  NaN  NaN    NaN
h  4.0  4.0    4.0


-----------------Checking for minimum values--------------

In [96]:
print(df['one'].isnull())

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool


In [91]:
print(df['two'].isnull())

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: two, dtype: bool


In [92]:
df.isnull().sum()

one      3
two      3
three    3
dtype: int64

-----------------Calculation with missing data---------------------
-------------While summing data nan will be considered as zero--------------
-------------If the data is all nan then the result will be nan------------

In [97]:
print(df)

   one  two  three
a  4.0  4.0    4.0
b  NaN  NaN    NaN
c  4.0  4.0    4.0
d  NaN  NaN    NaN
e  4.0  4.0    4.0
f  4.0  4.0    4.0
g  NaN  NaN    NaN
h  4.0  4.0    4.0


In [98]:
print(df['one'].sum())

20.0


In [99]:
df_NAN= pd.DataFrame(index=[1,2,3,4,5],columns=['one','two'])
print(df_NAN)

   one  two
1  NaN  NaN
2  NaN  NaN
3  NaN  NaN
4  NaN  NaN
5  NaN  NaN


In [100]:
print(df_NAN['one'].sum())

0


In [101]:
df_NAN['one'][2]=10
print(df_NAN, '\n')
print(df_NAN['one'].sum())

   one  two
1  NaN  NaN
2   10  NaN
3  NaN  NaN
4  NaN  NaN
5  NaN  NaN 

10


In [102]:
print(df_NAN)

   one  two
1  NaN  NaN
2   10  NaN
3  NaN  NaN
4  NaN  NaN
5  NaN  NaN


-----------------Replace Nan with a scaler qualtity 


In [126]:
print(np.random.rand(5,3), '\n\n')
df= pd.DataFrame(np.random.rand(5,3),index=['a','e','c','f','h'],columns=['one','two','three'])
print(df, '\n\n')
df=df.reindex(['l','a','b','c','d','e','f','g','h'])
print(df)

[[0.95638292 0.14709338 0.86701732]
 [0.61022686 0.85896787 0.37446025]
 [0.9434368  0.59232348 0.19430786]
 [0.38196575 0.15481818 0.56449832]
 [0.44035503 0.79559644 0.94604782]] 


        one       two     three
a  0.130389  0.377106  0.488789
e  0.635144  0.713676  0.967203
c  0.501802  0.673280  0.444972
f  0.455023  0.386075  0.199383
h  0.557536  0.853036  0.246809 


        one       two     three
l       NaN       NaN       NaN
a  0.130389  0.377106  0.488789
b       NaN       NaN       NaN
c  0.501802  0.673280  0.444972
d       NaN       NaN       NaN
e  0.635144  0.713676  0.967203
f  0.455023  0.386075  0.199383
g       NaN       NaN       NaN
h  0.557536  0.853036  0.246809


In [128]:
df_new_2 = df


In [120]:
print(df.fillna(method='ffill'))

        one       two     three
l       NaN       NaN       NaN
a  0.257217  0.404247  0.689591
b  0.257217  0.404247  0.689591
c  0.108081  0.906186  0.893482
d  0.108081  0.906186  0.893482
e  0.784096  0.809437  0.560446
f  0.828340  0.765223  0.896554
g  0.828340  0.765223  0.896554
h  0.521078  0.895302  0.799251


## method:- {‘backfill’, ‘bfill’, ‘pad’, ‘ffill’, None}, default None
#### Method to use for filling holes in reindexed Series
#### pad / ffill: propagate last valid observation forward to next valid
#### backfill / bfill: use NEXT valid observation to fill gap

In [ ]:
#df= pd.DataFrame(np.random.rand(5,3),index=['a','e','c','f','h'],columns=['one','two','three'])
#df=df.reindex(['a','b','c','d','e','f','g','h','t'])

print(df.fillna(method='backfill'))

--------------------------------Drop missing values---------------

In [121]:
df= pd.DataFrame(np.random.rand(5,3),index=['a','e','c','f','h'],
                 columns=['one','two','three'])
df=df.reindex(['a','b','c','d','e','f','g','h'])

#DRop all rows with NAN
print(df,'\n')
print(df.dropna(),'\n')#default , axis=0
print(df, '\n')
print(df.dropna(axis=0))

        one       two     three
a  0.723427  0.615590  0.515809
b       NaN       NaN       NaN
c  0.222586  0.505045  0.278368
d       NaN       NaN       NaN
e  0.851502  0.569986  0.179637
f  0.424538  0.917819  0.892791
g       NaN       NaN       NaN
h  0.003648  0.441923  0.350314 

        one       two     three
a  0.723427  0.615590  0.515809
c  0.222586  0.505045  0.278368
e  0.851502  0.569986  0.179637
f  0.424538  0.917819  0.892791
h  0.003648  0.441923  0.350314 

        one       two     three
a  0.723427  0.615590  0.515809
b       NaN       NaN       NaN
c  0.222586  0.505045  0.278368
d       NaN       NaN       NaN
e  0.851502  0.569986  0.179637
f  0.424538  0.917819  0.892791
g       NaN       NaN       NaN
h  0.003648  0.441923  0.350314 

        one       two     three
a  0.723427  0.615590  0.515809
c  0.222586  0.505045  0.278368
e  0.851502  0.569986  0.179637
f  0.424538  0.917819  0.892791
h  0.003648  0.441923  0.350314


In [122]:
#Drop all columns with NaN
print(df.dropna(axis=1))

Empty DataFrame
Columns: []
Index: [a, b, c, d, e, f, g, h]


----------Replacing missing or genric values---------

In [123]:
df=pd.DataFrame({'one':[10,20,30,40,50,2000],
                'two': [1000,20,0,30,45,60]})

print(df,'\n')
x=df.replace({1000:10,2000:20})  
print(x)
#print(df.replace({1000:10,2000:20}))

    one   two
0    10  1000
1    20    20
2    30     0
3    40    30
4    50    45
5  2000    60 

   one  two
0   10   10
1   20   20
2   30    0
3   40   30
4   50   45
5   20   60


# Series Operations

In [143]:
#create a series with random values
s=pd.Series(range(100,110),index=range(10,20))#np.random.rand(10))
print(s)

10    100
11    101
12    102
13    103
14    104
15    105
16    106
17    107
18    108
19    109
dtype: int64


In [144]:
print("THE axes are: ")
print(s.axes)

THE axes are: 
[RangeIndex(start=10, stop=20, step=1)]


In [145]:
s2=pd.Series(np.random.rand(4),index=[11,12,13,14])
print(s2)

11    0.801429
12    0.816339
13    0.999648
14    0.873051
dtype: float64


In [146]:
print("The axes are: ")
print(s2.axes)

The axes are: 
[Int64Index([11, 12, 13, 14], dtype='int64')]


In [147]:
se=pd.Series()
print(se,'\n')

print('Is this object empty?')
print(se.empty)

Series([], dtype: float64) 

Is this object empty?
True


In [148]:
print('Is this object empty?')
print(s.empty)

Is this object empty?
False


In [149]:
print("Dimiensions of the object: ")
print(s2.ndim)

Dimiensions of the object: 
1


In [150]:
print('The size of the object:')
print(s.size)

The size of the object:
10


In [151]:
print("The actual data series is: ")
print(s.values)

The actual data series is: 
[100 101 102 103 104 105 106 107 108 109]


In [152]:
print('The first two rows of the data series is: ')
print(s.head(2))

The first two rows of the data series is: 
10    100
11    101
dtype: int64


In [153]:
print('The last two rows are: ')
print(s.tail(2))

The last two rows are: 
18    108
19    109
dtype: int64


# Data Frames Operations

In [154]:
#create dictionary of series
d={'Name':pd.Series(['Chandler','Joey','Rachel','Ross','Monica','Phoebe']),
  'Age':pd.Series([32,29,30,33,35,36],dtype=np.int32),
   'Rating': pd.Series([10,9.9,9.5,9.99,8,8.5])}


In [155]:
#created a data frame
df=pd.DataFrame(d)
print("Our Data Frame is")
print(df)

Our Data Frame is
       Name  Age  Rating
0  Chandler   32   10.00
1      Joey   29    9.90
2    Rachel   30    9.50
3      Ross   33    9.99
4    Monica   35    8.00
5    Phoebe   36    8.50


In [156]:
print('The transpose of the data frame is :')
print(df.T)

The transpose of the data frame is :
               0     1       2     3       4       5
Name    Chandler  Joey  Rachel  Ross  Monica  Phoebe
Age           32    29      30    33      35      36
Rating        10   9.9     9.5  9.99       8     8.5


In [157]:
print('Rows axis lables and column axis lablels are:')
print(df.axes)

Rows axis lables and column axis lablels are:
[RangeIndex(start=0, stop=6, step=1), Index(['Name', 'Age', 'Rating'], dtype='object')]


In [158]:
print('The data types of each column are')
print(df.dtypes)

The data types of each column are
Name       object
Age         int32
Rating    float64
dtype: object


In [159]:
print('The dimension of the object are:')
print(df.ndim)

The dimension of the object are:
2


In [160]:
print("The shape of the frame is")
print(df.shape)

The shape of the frame is
(6, 3)


In [161]:
print('The total elements in the frame are:')
print(df.size)

The total elements in the frame are:
18


In [162]:
print('The actual data in the dat frame is: ')
print(df.values)

The actual data in the dat frame is: 
[['Chandler' 32 10.0]
 ['Joey' 29 9.9]
 ['Rachel' 30 9.5]
 ['Ross' 33 9.99]
 ['Monica' 35 8.0]
 ['Phoebe' 36 8.5]]


In [163]:
print("The first two rows are")
print(df.head(2))

The first two rows are
       Name  Age  Rating
0  Chandler   32    10.0
1      Joey   29     9.9


In [164]:
print("The lastt two rows are")
print(df.tail(2))

The lastt two rows are
     Name  Age  Rating
4  Monica   35     8.0
5  Phoebe   36     8.5


In [17]:
d = pd.read_csv('test.csv')

In [18]:
print(d)

   1  aa  a1
0  2  bb  b2
1  3  cc  c3
2  4  dd  d4


In [124]:
df_new = pd.DataFrame(d)

In [125]:
df_new

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [129]:
df_new_2

one       two     three
l       NaN       NaN       NaN
a  0.130389  0.377106  0.488789
b       NaN       NaN       NaN
c  0.501802  0.673280  0.444972
d       NaN       NaN       NaN
e  0.635144  0.713676  0.967203
f  0.455023  0.386075  0.199383
g       NaN       NaN       NaN
h  0.557536  0.853036  0.246809

In [130]:
df_new_2.to_csv('new.csv')

In [133]:
test_df = pd.read_csv('new2.txt')

In [134]:
test_df

1.aa.a1
0  2.bb.b2
1  3.cc.c3
2  4.dd.d4

In [142]:
t2 = pd.read_csv('new2.txt', sep='.', )
t2

1  aa  a1
0  2  bb  b2
1  3  cc  c3
2  4  dd  d4