In [3]:
import numpy as np

In [2]:
a= np.array([1,2,3,4])
b= np.array([10,20,30,40])
c=a+b
print(c)

[11 22 33 44]


In [3]:
m=a*b
print(m)

[ 10  40  90 160]


In [4]:
d=5*b
print(b)

[10 20 30 40]


In [6]:
a= np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b= np.array([1,2,3])
c= np.array([[1],[2],[3],[4]])


In [7]:
print("First Array: ")
print(a)

First Array: 
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [8]:
print("Second Array")
print(b)

Second Array
[1 2 3]


In [9]:
print("First array + Second Array")
print(a+b)

First array + Second Array
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [10]:
print(c)

[[1]
 [2]
 [3]
 [4]]


In [11]:
print(a+c)

[[ 1  1  1]
 [12 12 12]
 [23 23 23]
 [34 34 34]]


In [13]:
c=np.array([[1],[2],[3],[4],[5]])
print(c)
print(a+c)#Not broadcastable

[[1]
 [2]
 [3]
 [4]
 [5]]


ValueError: operands could not be broadcast together with shapes (4,3) (5,1) 

# Trignometric Calculations

In [21]:
a= np.array([0,30,45,60,90])

print("Sine of Different Angles")
#Convert to radians by multiplying by pi/180
print(np.sin(a*np.pi/180))
print('\n')


Sine of Different Angles
[0.         0.5        0.70710678 0.8660254  1.        ]




In [18]:
print("Cosine of different angles")
print(np.cos(a*np.pi/180))

Cosine of different angles
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [19]:
print("Values of tangent")
print(np.tan(a*np.pi/180))

Values of tangent
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


# Round Function 

In [3]:
a= np.array([1.0,5.55,123,0.567,25.532])

print("Original Array")
print(a)

Original Array
[  1.      5.55  123.      0.567  25.432]


In [4]:
print("After Rounding")
print(np.around(a))


After Rounding
[  1.   6. 123.   1.  25.]


In [5]:
print(np.around(a,decimals=1))#Upto 1 decimal space

[  1.    5.6 123.    0.6  25.4]


In [9]:
print(np.around(a,decimals=-1))
#Round of to the nearest 10

[  0.  10. 120.   0.  30.]


In [26]:
a=np.array([-1.7,1.5,-0.2,0.6,10])
print("The given array: ")
print(a)

The given array: 
[-1.7  1.5 -0.2  0.6 10. ]


In [27]:
print("The modified array")
print(np.floor(a))

The modified array
[-2.  1. -1.  0. 10.]


In [29]:
print("Ceiling of array")
print(np.ceil(a))

Ceiling of array
[-1.  2. -0.  1. 10.]


----------------------------
-------------------------------
Arithematic

In [4]:
a=np.arange(9,dtype=float).reshape(3,3)

print("First array: ")
print(a)

First array: 
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [31]:
print("Second array: ")
b=np.array([10,5,1])
print(b)

Second array: 
[10  5  1]


In [32]:
print("Add the two arrays")
print(np.add(a,b))

Add the two arrays
[[10.  6.  3.]
 [13.  9.  6.]
 [16. 12.  9.]]


In [33]:
print("Subtract the two arrays")
print(np.subtract(a,b))

Subtract the two arrays
[[-10.  -4.   1.]
 [ -7.  -1.   4.]
 [ -4.   2.   7.]]


In [34]:
print("Multiply the two arrays")
print(np.multiply(a,b))

Multiply the two arrays
[[ 0.  5.  2.]
 [30. 20.  5.]
 [60. 35.  8.]]


In [35]:
print("Divide the two arrays")
print(np.divide(a,b))

Divide the two arrays
[[0.  0.2 2. ]
 [0.3 0.8 5. ]
 [0.6 1.4 8. ]]


---------------------------------------------------

In [13]:
a=np.array([0.25,1.33,1,10,100])

print("Our array is")
print(a)

Our array is
[  0.25   1.33   1.    10.   100.  ]


In [14]:
print("After applying reciprocal function")
print(np.reciprocal(a))

After applying reciprocal function
[4.        0.7518797 1.        0.1       0.01     ]


In [43]:
b= np.array([100],dtype=int)
print("Second array is: ")
print(b)

Second array is: 
[100]


In [44]:
print("After reciprocal function")
print(np.reciprocal(b))#this is zero beacuse it's dtype is int, try with float it will be 0.01

After reciprocal function
[0]


---------------------------------------
--------------------------------
Power Functions

In [45]:
a=np.array([10,100,1000])

print("Our array is")
print(a)

Our array is
[  10  100 1000]


In [46]:
print("Applying power function ")
print(np.power(a,2))

Applying power function 
[    100   10000 1000000]


In [47]:
print("Second array is")
b=np.array([1,2,3])
print(b)

Second array is
[1 2 3]


In [49]:
print('Applying power function again')
print(np.power(a,b))

Applying power function again
[        10      10000 1000000000]


In [17]:
a=np.array([10,20,30])
b=np.array([3,5,7])

print("First array")
print(a)
print('\n')
print("Second Array")
print(b)

First array
[10 20 30]


Second Array
[3 5 7]


In [18]:
print("Applying mod function")
print(np.mod(a,b))

Applying mod function
[1 0 2]


In [19]:
print("Applying Remainder function")
print(np.remainder(a,b))

Applying Remainder function
[1 0 2]


In [56]:
help(np.mod)

Help on ufunc object:

remainder = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate a