# NumPy

In [2]:
import numpy as np

In [2]:
cvalues = [25.3, 24.8, 37, 23.9]
# List of temperature values in C
print( type(cvalues))
print(cvalues)

<class 'list'>
[25.3, 24.8, 37, 23.9]


In [3]:
C= np.array(cvalues)
print(C)
print(type(C))

[25.3 24.8 37.  23.9]
<class 'numpy.ndarray'>


In [4]:
#General conversion from C to F
fvalues =[]
print("Using Normal Method: ")
for x in cvalues:
    fvalues.append(x*9/5+32)
print(fvalues,'\n')

Using Normal Method: 
[77.54, 76.64, 98.6, 75.02] 



In [5]:
print('Numpy simple calculations: ')
print(C*9/5+32 )

Numpy simple calculations: 
[77.54 76.64 98.6  75.02]


In [6]:
c=cvalues*3
print(c)

[25.3, 24.8, 37, 23.9, 25.3, 24.8, 37, 23.9, 25.3, 24.8, 37, 23.9]


In [8]:
a= np.array([1,2,3], dtype='int16')
print(a)
#more that one dimensions
a= np.array([[1,2],[3,4]], order= 'C')
print(a)
#minimum dimensions
a= np.array([1,2,3,4,5,6], ndmin=3)
#here the min dim is 2, and the matrix made in a row matrix, you can see the double bracckets in the output
print(a)



[1 2 3]
[[1 2]
 [3 4]]
[[[1 2 3 4 5 6]]]


# DDD

In [15]:
dt= np.dtype(np.int32)
print(dt)

int32


In [13]:
#int8,int16,int32,int64 can be replaced
#by equivalent string 'i1','i2','i4' etc
dt=np.dtype('i4')
print(dt)


int32


In [9]:
#first create structured data type
dt= np.dtype([('age',np.int8),('weight',np.int32)])
print(dt)
c=()

[('age', 'i1'), ('weight', '<i4')]


In [10]:
#now apply it to ndarray object
a= np.array([(10,50),(20,60),(30,30)], dtype=dt)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[(10, 50) (20, 60) (30, 30)]


In [11]:
#array name can be used to access content of age coloumn
print(a['weight'])

[50 60 30]


In [12]:
x1=(10)
x2=(10,)
print(x1, type(x1))
print(x2, type(x2))

10 <class 'int'>
(10,) <class 'tuple'>


In [21]:
student= np.dtype([('name','S2'), ('age', 'i1') , ('marks','f4')])
print(student)

[('name', 'S2'), ('age', 'i1'), ('marks', '<f4')]


In [22]:
a=np.array([('abc', 21 ,50), ('xyz',18,75)], dtype= student)
print(a)
print(a.itemsize)

[(b'ab', 21, 50.) (b'xy', 18, 75.)]
7


In [18]:
print(a['age'])
print(a['name'][1])
print(a['marks'])

[21 18]
b'xy'
[50. 75.]


# Attributes

In [46]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [47]:
#this resizes the array
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [48]:
#back to normal
a.shape=(2,30)
print(a)

ValueError: cannot reshape array of size 6 into shape (2,30)

In [20]:
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3, 2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [29]:
#an array of evenly spaced numbers
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [26]:
#an array of evenly distributed numbers
n = np.linspace(start=0, stop=19, num=10, dtype='int')
print(n)

[ 0  2  4  6  8 10 12 14 16 19]


In [27]:
#Above is a one dimension array
print(a.ndim)

1


In [33]:
#now reshape it
print(a,'\n\n')
b=a.reshape(4,6, order='F')
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 


[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


In [31]:
#b is having 2 dimensions
print(b.ndim)

2


In [81]:
#dtype of array is int8 (1 byte)
x= np.array([1,2,3,4,5], dtype=np.int32)
print(x.itemsize)

4


In [75]:
#dtype of array is float32 (4 byte)
x= np.array([1,2,3,4,5], dtype=np.float32)
print(x.itemsize)

4


In [31]:
###
student=np.dtype([('name','S20'),('age','i1'),('marks','f4')])

a= np.array([('abc',21,50),('xyz',18,75)],dtype=student)
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [41]:
x=np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [45]:
print(x.flags['WRITEABLE'])

True


In [46]:
x[3]=10
print(x)

[ 1  2  3 10  5]


In [48]:
x.flags['WRITEABLE']= False
x[1]=12
print(x)
##ValueError: assignment destination is read only
#As the writeable flag was conevrted to False we can't write in it any more

ValueError: assignment destination is read-only

# Creation

In [87]:
x=np.empty([4,7],dtype=int)
print(x)#garbage vALUE

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [90]:
#array of 5 zeros. Default dtype is float
x= np.zeros([4,7])
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [54]:
x=np.zeros(5, dtype=int)
print(x)

[0 0 0 0 0]


In [46]:
#custom type
x= np.zeros((2,2), dtype=[('x','i4'),('y','float32')])
print(x)

[[(0, 0.) (0, 0.)]
 [(0, 0.) (0, 0.)]]


In [12]:
#array of 5 ones , default dtype is float
x=np.ones([4,7])
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [3]:
#in int
x= np.ones([2,2],dtype=int)
print(x)

[[1 1]
 [1 1]]


-----------------------------
------------------------
-------------------------------
Some more custom types and editing them

In [13]:
v= np.zeros([2,2], dtype=[('x','i4'),('y','i4')])
print(v)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [44]:
v['y'][0][0]=6 
print(v)

[[(0, 6) (0, 0)]
 [(0, 0) (0, 0)]]


In [45]:
v['x'][0]=(8,9)
print(v)

[[(8, 6) (9, 0)]
 [(0, 0) (0, 0)]]


# More on numpy

In [49]:
#convert list to ndarray
x=[1,2,3]
a= np.asarray(x)
print(type(x))
print(type(a))
print(a)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3]


In [69]:
#dtype is set
a= np.asarray(x,dtype=float)
print(a)

[1. 2. 3.]


In [4]:
#ndarray from tuple
x=(1,2,3)
a= np.asarray(x)
print(a)

[1 2 3]


In [42]:
s=b'Hello World '
a= np.frombuffer(s,count=6,offset=0,dtype='S2')#count gives no. of elements to read ,to read all elements count=-1
print(a)

[b'He' b'll' b'o ' b'Wo' b'rl' b'd ']


In [113]:
#help(np.frombuffer)

# Array range functions

In [83]:
x=np.arange(5)
print(x)

[0 1 2 3 4]


In [58]:
#dtype set
x= np.arange(5,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [86]:
#start n stop parameters set
x= np.arange(10,20,2)
print(x)

[10 12 14 16 18]


-------------------------------
--------------------------
linrange function

In [54]:
x=np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [51]:
#endpoint set to false
x=np.linspace(10,20,5,endpoint=False)#read help
print(x)
print(type(x))

[10. 12. 14. 16. 18.]
<class 'numpy.ndarray'>


In [95]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [67]:
#find retstep value
x=np.linspace(1,2,5,retstep=True)
print(x)

#(stop-start)/(num-1)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


# Indexing and slicing

In [116]:
a=np.arange(10,21,1)
s=slice(2,7,2)#using the slice function
print(a)
print('\n')
print(a[s])

[10 11 12 13 14 15 16 17 18 19 20]


[12 14 16]


In [118]:
a=np.arange(10,21,1)
print(a)

[10 11 12 13 14 15 16 17 18 19 20]


In [119]:
b=a[2:7]
print(b)

[12 13 14 15 16]


In [120]:
#slice single item
a= np.arange(10)
b=a[5]
print(b)
print(a)

5
[0 1 2 3 4 5 6 7 8 9]


In [121]:
#slice items starting from index
a=np.arange(10)
print(a[:5])

[0 1 2 3 4]


In [128]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [129]:
#slice items starting from index
print('Now we will slice the array of the index a[1:]')
print(a[1:])

Now we will slice the array of the index a[1:]
[[4 5 6]
 [7 8 9]]


In [130]:
print(a.ndim)

2


In [137]:
print(a[:][:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
#This returns arrays of items in the second coloumn
print('The items in the second coloumn are:')
print(a[...,1])
print('\n')

The items in the second coloumn are:
[2 5 8]




In [111]:
#now we will slice the items in the second row
print('The items in the second row are: ')
print(a[1,...])

The items in the second row are: 
[4 5 6]


In [23]:
#now we will slice all items from coloumn one onwards
print('The items coloumn 1 onwards are: ')
print(a[...,1:])
print('\n')
print(a[1:,...])

The items coloumn 1 onwards are: 
[[2 3]
 [5 6]
 [8 9]]


[[4 5 6]
 [7 8 9]]


# Advance slicing

In [141]:
x=np.array([[1,2],[3,4],[5,6]])
y=x[[1,2],[1,0]]#it picks the row no. from the first list and coloumn no. from 2nd list
print(x)
print('\n')
print(y)

[[1 2]
 [3 4]
 [5 6]]


[4 5]


In [44]:
x= np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [46]:
rows= np.array([[0,0],[3,3]])
cols= np.array([[0,2],[0,2]])
print(rows)
print(cols)
y=x[rows,cols]

print('The corner elements of the array are:')
print(y)


[[0 0]
 [3 3]]
[[0 2]
 [0 2]]
The corner elements of the array are:
[[ 0  2]
 [ 9 11]]


In [144]:
r=np.array([[1,0,1],[0,3,2]])
c=np.array([[0,1,2],[2,1,2]])
y=x[r,c]
print(y)

[[ 3  1  5]
 [ 2 10  8]]


In [145]:
print('Our array is: ')
print(x)
print('\n')


Our array is: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]




In [157]:
#slicing
z=x[1:4,1:3]
print('After slicing our array becomes: ')
print(z)

After slicing our array becomes: 
[[ 4  5]
 [ 7  8]
 [10 11]]


In [100]:
#using advance index for coloumn
y=x[1:4,[1,2]]
print('Slicing using advance indexing for column')
print(y)
    


Slicing using advance indexing for column
[[ 4  5]
 [ 7  8]
 [10 11]]


In [130]:
x=np.arange(12)
print('Our array is: ')
print(x)

Our array is: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [131]:
#now we will print the items greater than 5
print('the items greater than 5 are: ')
print(x[x>5])#this will return a boolean

the items greater than 5 are: 
[ 6  7  8  9 10 11]


In [133]:
a=np.array([np.nan,1,2,np.nan,3,4,5])
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [135]:
a=np.array([1,2+6j,5,3.5+5j])
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]
